### ISSUE TITLE
 Error when sending a tip, when you have just received a tip

### ISSUE THREAD

**Issue by sak963** [codeBrice/helios-tipbot#1]
Error when sending a tip, when you have just received a tip

example:
user1 tip a user2:
**.tip 1 @user2**
success

user2 tip a user3
**.tip 1 @user3**
error

**Comment by codeBrice** [comment]
@sak963 esto debe funcionar igual al bitbucket

**Comment by codeBrice** [comment]
Fix in the commit e3c1b9c48ad79e5c60058ff6abdb5835db203a6b
